{% set name = "robocorp-workitems" %}
{% set version = "1.4.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/robocorp_workitems-{{ version }}.tar.gz
  sha256: c88734892fcb6c12c78fdb003cb5aadbc0c4227e540993aae3f832699af59ad1

build:
  noarch: python
  script:
    - echo f | xcopy /f /y /S %RECIPE_DIR%\README.md %SRC_DIR%\README.md  # [win]
    - cp -R {{ RECIPE_DIR }}/README.md {{ SRC_DIR }}/README.md  # [unix]
    - {{ PYTHON }} -m pip install . -vv
  number: 0
requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - marshmallow
    - python >={{ python_min }},<4.0.0
    - robocorp-tasks >=1,<5
    - requests >=2.28.2,<3.0.0
    - tenacity >=8.0.1,<9.0.0
    - dataclasses-json >=0.6.1,<0.7.0
    - python-dateutil >=2.8.2,<3.0.0

test:
  imports:
    - robocorp.workitems
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/robocorp/robocorp/
  summary: Robocorp Work Items library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - zaigner
